## Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


The key idea is to provide a nested list or array that represents the data and its dimensions. Each nested level corresponds to a new dimension in the tensor. The length of each nested list along each dimension determines the size of that dimension.

tf.constant is used to create tensors with constant values that cannot be changed once defined. The values of a constant tensor remain fixed throughout the execution of the program.

Constants are useful when you have data that won't change during the training or inference process. They are typically used to represent model parameters, hyperparameters, or any other fixed data that your model needs.

In [18]:
#Creating tensors : scalar , vectors , n dimensional tensors using tf.constant()
scalar = tf.constant(7)
print(f"dimensions of the scalar is {scalar.ndim} and shape is {scalar.shape}")

vector = tf.constant([7,7])
print(f"dimensions of the vector is {vector.ndim} and shape is {vector.shape}")


matrix = tf.constant([[7,7],[7,7]])
print(f"dimensions of the matrix is {matrix.ndim} and shape is {matrix.shape}")

tensor = tf.constant([[[7,7],[7,7],[7,7]]])
print(f"dimensions of the tensor is {tensor.ndim} and shape is {tensor.shape}")

tensor_4 = tf.constant([[[[7,7],[7,7],[2,10]]]])
print(f"dimensions of the tensor_4 is {tensor_4.ndim} and shape is {tensor_4.shape}")


dimensions of the scalar is 0 and shape is ()
dimensions of the vector is 1 and shape is (2,)
dimensions of the matrix is 2 and shape is (2, 2)
dimensions of the tensor is 3 and shape is (1, 3, 2)
dimensions of the tensor_4 is 4 and shape is (1, 1, 3, 2)


tf.Variable is used to create tensors that can be modified during the execution of the program. The values of a variable tensor can be updated or changed using TensorFlow operations like assign or assign_add.

Variables are commonly used to represent the trainable parameters of a machine learning model. These parameters are updated during training to minimize the loss function and improve model performance.

In [22]:
#creating tensors using tf.Variable
changeable_tensor = tf.Variable([10,7])
print(f"{changeable_tensor[0]}")
changeable_tensor[0].assign(7)
print(f"{changeable_tensor[0]}")

10
7


In [24]:
#Shuffling the order of a tensor means randomly permuting its elements along a given axis.
#This is often useful in machine learning, especially during data preprocessing and when you want to randomize the order of your data for training.
original_tensor = tf.constant([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])

# Shuffling along the first dimension (rows)
shuffled_tensor = tf.random.shuffle(original_tensor)

print("Original Tensor:")
print(original_tensor)

print("\nShuffled Tensor:")
print(shuffled_tensor)

shuffled_tensor = tf.random.shuffle(original_tensor, seed=42)

print("\nShuffled Tensor with Seed:")
print(shuffled_tensor)

Original Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

Shuffled Tensor:
tf.Tensor(
[[4 5 6]
 [1 2 3]
 [7 8 9]], shape=(3, 3), dtype=int32)

Shuffled Tensor with Seed:
tf.Tensor(
[[7 8 9]
 [4 5 6]
 [1 2 3]], shape=(3, 3), dtype=int32)


# Manipulation of Tensors
1. Information
2. Indexing
3. Braodcasting
4. Basic Operations
5. Advanced Operations : Squeezing , Encoding ,

In [25]:
# Constant Tensor
const_tensor = tf.constant([[1, 2, 3],[4, 5, 6]])
# Variable Tensor
var_tensor = tf.Variable([[7, 8],[9, 10],[11, 12]])

In [27]:
print("Shape:", const_tensor.shape)
print("Axis 1 Shape:", const_tensor.shape[1])
print("Rank:", tf.rank(const_tensor))
print("Dimension 0:", tf.shape(const_tensor)[0])
print("Dimension 1:", tf.shape(const_tensor)[1])

Shape: (2, 3)
Axis 1 Shape: 3
Rank: tf.Tensor(2, shape=(), dtype=int32)
Dimension 0: tf.Tensor(2, shape=(), dtype=int32)
Dimension 1: tf.Tensor(3, shape=(), dtype=int32)


In [29]:
print(var_tensor)
print("Shape:", var_tensor.shape)
# Reshaping the Variable Tensor to have 1 dimension (Flattening the tensor)
var_flat = tf.reshape(var_tensor, [-1])

# Printing the reshaped tensor
print("\nReshaped Variable Tensor (Flattened):")
print(var_flat)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>
Shape: (3, 2)

Reshaped Variable Tensor (Flattened):
tf.Tensor([ 7  8  9 10 11 12], shape=(6,), dtype=int32)


In [31]:
#Indexing
print(const_tensor[0])  # Accessing the first element (output: 1)
print(const_tensor[1:4])  # Slicing elements from index 1 to 3 (output: [2 3 4])

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([[4 5 6]], shape=(1, 3), dtype=int32)


Expanding (also known as broadcasting) is a concept in tensor operations that enables you to perform operations between tensors with different shapes or dimensions. When you perform operations between tensors that have different shapes, TensorFlow automatically "expands" the smaller tensor to match the shape of the larger tensor. This process allows element-wise operations to be performed even when the tensor shapes are not identical.

In [36]:
print(const_tensor)
expanded_tensor = tf.expand_dims(const_tensor, axis=0)
print(expanded_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)


In [32]:
tensor_a = tf.constant([[1, 2, 3],[4, 5, 6]])
scalar_b = tf.constant(10)
# Adding a scalar to each element of the tensor using broadcasting
result = tensor_a + scalar_b
print(result)

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)


In [39]:
print(tensor_a+10)
print(tensor_a-10)
print(tensor_a*10)
print(tensor_a/10)

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-9 -8 -7]
 [-6 -5 -4]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]], shape=(2, 3), dtype=float64)


tf.add: Element-wise addition of two tensors.

tf.pow: Element-wise exponentiation of a tensor.

tf.sin, tf.cos, tf.tan: Element-wise trigonometric functions.

tf.reduce_sum: Computes the sum of elements across specified dimensions. This is called aggregating

tf.cast(tensor, dtype): change the data type elementwise

In [40]:
  # Synatx : tf.matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)
mat_multi = tf.matmul(tensor_a, scalar_b)
print(mat_multi)

InvalidArgumentError: ignored

In TensorFlow, matrix multiplication is performed using the tf.matmul() function or the @ operator.

The tf.matmul() function takes two tensors as input and performs matrix multiplication between them.

The function follows the standard mathematical rules for matrix multiplication, where the number of columns in the first matrix must be equal to the number of rows in the second matrix.

Matrix multiplication is only defined for tensors with rank 2 or higher, and you cannot directly perform matrix multiplication between a 2D tensor and a scalar.

In [41]:
matrix_a = tf.constant([[1, 2],
                        [3, 4]])

matrix_b = tf.constant([[5, 6],
                        [7, 8]])

# Perform matrix multiplication using tf.matmul()
result = tf.matmul(matrix_a, matrix_b)

print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

print("\nResult of Matrix Multiplication:")
print(result)


Matrix A:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Matrix B:
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)

Result of Matrix Multiplication:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


"squeezing" refers to the operation of removing dimensions with size 1 from a tensor. A tensor is a multi-dimensional array that can have various dimensions, and sometimes, certain dimensions may have a size of 1, which can be unnecessary or redundant in certain calculations.

For example, let's say we have a tensor A of shape (3, 1, 4). This means it has 3 rows, 1 column, and 4 channels. However, having a single column (size 1) might not be required for certain operations, and we might prefer to work with a tensor of shape (3, 4). To achieve this, we can "squeeze" the tensor along the second dimension to remove the dimension with size 1.

In [7]:
A = tf.constant([[[1, 2, 3, 4]], [[5, 6, 7, 8]], [[9, 10, 11, 12]]])
# Squeeze the tensor to remove the dimension with size 1
B = tf.squeeze(A)
B.shape

TensorShape([3, 4])

In [10]:
C = [1,2,3,4]
tf.one_hot(C,depth=3)
tf.one_hot(C,depth=4,on_value="wizzle",off_value="x")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'x', b'wizzle', b'x', b'x'],
       [b'x', b'x', b'wizzle', b'x'],
       [b'x', b'x', b'x', b'wizzle'],
       [b'x', b'x', b'x', b'x']], dtype=object)>